BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "Books" (
	"BookID"	INTEGER NOT NULL UNIQUE,
	"Chapters"	INTEGER NOT NULL,
	"Title"	TEXT NOT NULL,
	PRIMARY KEY("BookID" AUTOINCREMENT)
);
INSERT INTO "Books" VALUES (1,50,'Genesis');
INSERT INTO "Books" VALUES (2,40,'Exodus');
INSERT INTO "Books" VALUES (3,27,'Leviticus');
INSERT INTO "Books" VALUES (4,36,'Numbers');
INSERT INTO "Books" VALUES (5,34,'Deuteronomy');
INSERT INTO "Books" VALUES (6,24,'Joshua');
INSERT INTO "Books" VALUES (7,21,'Judges');
INSERT INTO "Books" VALUES (8,4,'Ruth');
INSERT INTO "Books" VALUES (9,31,'1 Samuel');
INSERT INTO "Books" VALUES (10,24,'2 Samuel');
INSERT INTO "Books" VALUES (11,22,'1 Kings');
INSERT INTO "Books" VALUES (12,25,'2 Kings');
INSERT INTO "Books" VALUES (13,29,'1 Chronicles');
INSERT INTO "Books" VALUES (14,36,'2 Chronicles');
INSERT INTO "Books" VALUES (15,10,'Ezra');
INSERT INTO "Books" VALUES (16,13,'Nehemiah');
INSERT INTO "Books" VALUES (17,10,'Esther');
INSERT INTO "Books" VALUES (18,42,'Job');
INSERT INTO "Books" VALUES (19,150,'Psalms');
INSERT INTO "Books" VALUES (20,31,'Proverbs');
INSERT INTO "Books" VALUES (21,12,'Ecclesiastes');
INSERT INTO "Books" VALUES (22,8,'Song of Solomon');
INSERT INTO "Books" VALUES (23,66,'Isaiah');
INSERT INTO "Books" VALUES (24,52,'Jeremiah');
INSERT INTO "Books" VALUES (25,5,'Lamentations');
INSERT INTO "Books" VALUES (26,48,'Ezekiel');
INSERT INTO "Books" VALUES (27,12,'Daniel');
INSERT INTO "Books" VALUES (28,14,'Hosea');
INSERT INTO "Books" VALUES (29,3,'Joel');
INSERT INTO "Books" VALUES (30,9,'Amos');
INSERT INTO "Books" VALUES (31,1,'Obadiah');
INSERT INTO "Books" VALUES (32,4,'Jonah');
INSERT INTO "Books" VALUES (33,7,'Micah');
INSERT INTO "Books" VALUES (34,3,'Nahum');
INSERT INTO "Books" VALUES (35,3,'Habakkuk');
INSERT INTO "Books" VALUES (36,3,'Zephaniah');
INSERT INTO "Books" VALUES (37,2,'Haggai');
INSERT INTO "Books" VALUES (38,14,'Zechariah');
INSERT INTO "Books" VALUES (39,4,'Malachi');
INSERT INTO "Books" VALUES (40,28,'Matthew');
INSERT INTO "Books" VALUES (41,16,'Mark');
INSERT INTO "Books" VALUES (42,24,'Luke');
INSERT INTO "Books" VALUES (43,21,'John');
INSERT INTO "Books" VALUES (44,28,'Acts');
INSERT INTO "Books" VALUES (45,16,'Romans');
INSERT INTO "Books" VALUES (46,16,'1 Corinthians');
INSERT INTO "Books" VALUES (47,13,'2 Corinthians');
INSERT INTO "Books" VALUES (48,6,'Galatians');
INSERT INTO "Books" VALUES (49,6,'Ephesians');
INSERT INTO "Books" VALUES (50,4,'Philippians');
INSERT INTO "Books" VALUES (51,4,'Colossians');
INSERT INTO "Books" VALUES (52,5,'1 Thessalonians');
INSERT INTO "Books" VALUES (53,3,'2 Thessalonians');
INSERT INTO "Books" VALUES (54,6,'1 Timothy');
INSERT INTO "Books" VALUES (55,4,'2 Timothy');
INSERT INTO "Books" VALUES (56,3,'Titus');
INSERT INTO "Books" VALUES (57,1,'Philemon');
INSERT INTO "Books" VALUES (58,13,'Hebrews');
INSERT INTO "Books" VALUES (59,5,'James');
INSERT INTO "Books" VALUES (60,5,'1 Peter');
INSERT INTO "Books" VALUES (61,3,'2 Peter');
INSERT INTO "Books" VALUES (62,5,'1 John');
INSERT INTO "Books" VALUES (63,1,'2 John');
INSERT INTO "Books" VALUES (64,1,'3 John');
INSERT INTO "Books" VALUES (65,1,'Jude');
INSERT INTO "Books" VALUES (66,22,'Revelation');
COMMIT;
