UPDATE KJAVerses SET BookID = 1, Book = "Genesis" WHERE Book = "GEN";
UPDATE KJAVerses SET BookID = 2, Book = "Exodus" WHERE Book = "EXO";
UPDATE KJAVerses SET BookID = 3, Book = "Leviticus" WHERE Book = "LEV";
UPDATE KJAVerses SET BookID = 4, Book = "Numbers" WHERE Book = "NUM";
UPDATE KJAVerses SET BookID = 5, Book = "Deuteronomy" WHERE Book = "DEU";
UPDATE KJAVerses SET BookID = 6, Book = "Joshua" WHERE Book = "JOS";
UPDATE KJAVerses SET BookID = 7, Book = "Judges" WHERE Book = "JDG";
UPDATE KJAVerses SET BookID = 8, Book = "Ruth" WHERE Book = "RUT";
UPDATE KJAVerses SET BookID = 9, Book = "1 Samuel" WHERE Book = "1SA";
UPDATE KJAVerses SET BookID = 10, Book = "2 Samuel" WHERE Book = "2SA";
UPDATE KJAVerses SET BookID = 11, Book = "1 Kings" WHERE Book = "1KI";
UPDATE KJAVerses SET BookID = 12, Book = "2 Kings" WHERE Book = "2KI";
UPDATE KJAVerses SET BookID = 13, Book = "1 Chronicles" WHERE Book = "1CH";
UPDATE KJAVerses SET BookID = 14, Book = "2 Chronicles" WHERE Book = "2CH";
UPDATE KJAVerses SET BookID = 15, Book = "Ezra" WHERE Book = "EZR";
UPDATE KJAVerses SET BookID = 16, Book = "Nehemiah" WHERE Book = "NEH";
UPDATE KJAVerses SET BookID = 17, Book = "Esther" WHERE Book = "EST";
UPDATE KJAVerses SET BookID = 18, Book = "Job" WHERE Book = "JOB";
UPDATE KJAVerses SET BookID = 19, Book = "Psalms" WHERE Book = "PSA";
UPDATE KJAVerses SET BookID = 20, Book = "Proverbs" WHERE Book = "PRO";
UPDATE KJAVerses SET BookID = 21, Book = "Ecclesiastes" WHERE Book = "ECC";
UPDATE KJAVerses SET BookID = 22, Book = "Song of Solomon" WHERE Book = "SNG";
UPDATE KJAVerses SET BookID = 23, Book = "Isaiah" WHERE Book = "ISA";
UPDATE KJAVerses SET BookID = 24, Book = "Jeremiah" WHERE Book = "JER";
UPDATE KJAVerses SET BookID = 25, Book = "Lamentations" WHERE Book = "LAM";
UPDATE KJAVerses SET BookID = 26, Book = "Ezekiel" WHERE Book = "EZK";
UPDATE KJAVerses SET BookID = 27, Book = "Daniel" WHERE Book = "DAN";
UPDATE KJAVerses SET BookID = 28, Book = "Hosea" WHERE Book = "HOS";
UPDATE KJAVerses SET BookID = 29, Book = "Joel" WHERE Book = "JOL";
UPDATE KJAVerses SET BookID = 30, Book = "Amos" WHERE Book = "AMO";
UPDATE KJAVerses SET BookID = 31, Book = "Obadiah" WHERE Book = "OBA";
UPDATE KJAVerses SET BookID = 32, Book = "Jonah" WHERE Book = "JON";
UPDATE KJAVerses SET BookID = 33, Book = "Micah" WHERE Book = "MIC";
UPDATE KJAVerses SET BookID = 34, Book = "Nahum" WHERE Book = "NAM";
UPDATE KJAVerses SET BookID = 35, Book = "Habakkuk" WHERE Book = "HAB";
UPDATE KJAVerses SET BookID = 36, Book = "Zephaniah" WHERE Book = "ZEP";
UPDATE KJAVerses SET BookID = 37, Book = "Haggai" WHERE Book = "HAG";
UPDATE KJAVerses SET BookID = 38, Book = "Zechariah" WHERE Book = "ZEC";
UPDATE KJAVerses SET BookID = 39, Book = "Malachi" WHERE Book = "MAL";
UPDATE KJAVerses SET BookID = 40, Book = "Tobit" WHERE Book = "TOB";
UPDATE KJAVerses SET BookID = 41, Book = "Judith" WHERE Book = "JDT";
UPDATE KJAVerses SET BookID = 42, Book = "Esther 10-16(Greek)" WHERE Book = "ESG";
UPDATE KJAVerses SET BookID = 43, Book = "Wisdom of Solomon" WHERE Book = "WIS";
UPDATE KJAVerses SET BookID = 44, Book = "Sirach" WHERE Book = "SIR";
UPDATE KJAVerses SET BookID = 45, Book = "Baruch" WHERE Book = "BAR";
UPDATE KJAVerses SET BookID = 46, Book = "3 Holy Children's Song" WHERE Book = "S3Y";
UPDATE KJAVerses SET BookID = 47, Book = "Susanna" WHERE Book = "SUS";
UPDATE KJAVerses SET BookID = 48, Book = "Bel and the Dragon" WHERE Book = "BEL";
UPDATE KJAVerses SET BookID = 49, Book = "1 Maccabees" WHERE Book = "1MA";
UPDATE KJAVerses SET BookID = 50, Book = "2 Maccabees" WHERE Book = "2MA";
UPDATE KJAVerses SET BookID = 51, Book = "1 Esdras" WHERE Book = "1ES";
UPDATE KJAVerses SET BookID = 52, Book = "Prayer of Manasses" WHERE Book = "MAN";
UPDATE KJAVerses SET BookID = 53, Book = "2 Esdras" WHERE Book = "2ES";
UPDATE KJAVerses SET BookID = 54, Book = "Matthew" WHERE Book = "MAT";
UPDATE KJAVerses SET BookID = 55, Book = "Mark" WHERE Book = "MRK";
UPDATE KJAVerses SET BookID = 56, Book = "Luke" WHERE Book = "LUK";
UPDATE KJAVerses SET BookID = 57, Book = "John" WHERE Book = "JHN";
UPDATE KJAVerses SET BookID = 58, Book = "Acts" WHERE Book = "ACT";
UPDATE KJAVerses SET BookID = 59, Book = "Romans" WHERE Book = "ROM";
UPDATE KJAVerses SET BookID = 60, Book = "1 Corinthians" WHERE Book = "1CO";
UPDATE KJAVerses SET BookID = 61, Book = "2 Corinthians" WHERE Book = "2CO";
UPDATE KJAVerses SET BookID = 62, Book = "Galatians" WHERE Book = "GAL";
UPDATE KJAVerses SET BookID = 63, Book = "Ephesians" WHERE Book = "EPH";
UPDATE KJAVerses SET BookID = 64, Book = "Philippians" WHERE Book = "PHP";
UPDATE KJAVerses SET BookID = 65, Book = "Colossians" WHERE Book = "COL";
UPDATE KJAVerses SET BookID = 66, Book = "1 Thessalonians" WHERE Book = "1TH";
UPDATE KJAVerses SET BookID = 67, Book = "2 Thessalonians" WHERE Book = "2TH";
UPDATE KJAVerses SET BookID = 68, Book = "1 Timothy" WHERE Book = "1TI";
UPDATE KJAVerses SET BookID = 69, Book = "2 Timothy" WHERE Book = "2TI";
UPDATE KJAVerses SET BookID = 70, Book = "Titus" WHERE Book = "TIT";
UPDATE KJAVerses SET BookID = 71, Book = "Philemon" WHERE Book = "PHM";
UPDATE KJAVerses SET BookID = 72, Book = "Hebrews" WHERE Book = "HEB";
UPDATE KJAVerses SET BookID = 73, Book = "James" WHERE Book = "JAS";
UPDATE KJAVerses SET BookID = 74, Book = "1 Peter" WHERE Book = "1PE";
UPDATE KJAVerses SET BookID = 75, Book = "2 Peter" WHERE Book = "2PE";
UPDATE KJAVerses SET BookID = 76, Book = "1 John" WHERE Book = "1JN";
UPDATE KJAVerses SET BookID = 77, Book = "2 John" WHERE Book = "2JN";
UPDATE KJAVerses SET BookID = 78, Book = "3 John" WHERE Book = "3JN";
UPDATE KJAVerses SET BookID = 79, Book = "Jude" WHERE Book = "JUD";
UPDATE KJAVerses SET BookID = 80, Book = "Revelation" WHERE Book = "REV";