UPDATE TYNVerses SET Book = "Genesis" WHERE BookID = 1;
UPDATE TYNVerses SET Book = "Exodus" WHERE BookID = 2;
UPDATE TYNVerses SET Book = "Leviticus" WHERE BookID = 3;
UPDATE TYNVerses SET Book = "Numbers" WHERE BookID = 4;
UPDATE TYNVerses SET Book = "Deuteronomy" WHERE BookID = 5;
UPDATE TYNVerses SET Book = "Jonah" WHERE BookID = 6;
UPDATE TYNVerses SET Book = "Matthew" WHERE BookID = 7;
UPDATE TYNVerses SET Book = "Mark" WHERE BookID = 8;
UPDATE TYNVerses SET Book = "Luke" WHERE BookID = 9;
UPDATE TYNVerses SET Book = "John" WHERE BookID = 10;
UPDATE TYNVerses SET Book = "Acts" WHERE BookID = 11;
UPDATE TYNVerses SET Book = "Romans" WHERE BookID = 12;
UPDATE TYNVerses SET Book = "1 Corinthians" WHERE BookID = 13;
UPDATE TYNVerses SET Book = "2 Corinthians" WHERE BookID = 14;
UPDATE TYNVerses SET Book = "Galatians" WHERE BookID = 15;
UPDATE TYNVerses SET Book = "Ephesians" WHERE BookID = 16;
UPDATE TYNVerses SET Book = "Philippians" WHERE BookID = 17;
UPDATE TYNVerses SET Book = "Colossians" WHERE BookID = 18;
UPDATE TYNVerses SET Book = "1 Thessalonians" WHERE BookID = 19;
UPDATE TYNVerses SET Book = "2 Thessalonians" WHERE BookID = 20;
UPDATE TYNVerses SET Book = "1 Timothy" WHERE BookID = 21;
UPDATE TYNVerses SET Book = "2 Timothy" WHERE BookID = 22;
UPDATE TYNVerses SET Book = "Titus" WHERE BookID = 23;
UPDATE TYNVerses SET Book = "Philemon" WHERE BookID = 24;
UPDATE TYNVerses SET Book = "Hebrews" WHERE BookID = 25;
UPDATE TYNVerses SET Book = "James" WHERE BookID = 26;
UPDATE TYNVerses SET Book = "1 Peter" WHERE BookID = 27;
UPDATE TYNVerses SET Book = "2 Peter" WHERE BookID = 28;
UPDATE TYNVerses SET Book = "1 John" WHERE BookID = 29;
UPDATE TYNVerses SET Book = "2 John" WHERE BookID = 30;
UPDATE TYNVerses SET Book = "3 John" WHERE BookID = 31;
UPDATE TYNVerses SET Book = "Jude" WHERE BookID = 32;
UPDATE TYNVerses SET Book = "Revelation" WHERE BookID = 33;