UPDATE GNVVerses SET Book = "Genesis" WHERE BookID = 1;
UPDATE GNVVerses SET Book = "Exodus" WHERE BookID = 2;
UPDATE GNVVerses SET Book = "Leviticus" WHERE BookID = 3;
UPDATE GNVVerses SET Book = "Numbers" WHERE BookID = 4;
UPDATE GNVVerses SET Book = "Deuteronomy" WHERE BookID = 5;
UPDATE GNVVerses SET Book = "Joshua" WHERE BookID = 6;
UPDATE GNVVerses SET Book = "Judges" WHERE BookID = 7;
UPDATE GNVVerses SET Book = "Ruth" WHERE BookID = 8;
UPDATE GNVVerses SET Book = "1 Samuel" WHERE BookID = 9;
UPDATE GNVVerses SET Book = "2 Samuel" WHERE BookID = 10;
UPDATE GNVVerses SET Book = "1 Kings" WHERE BookID = 11;
UPDATE GNVVerses SET Book = "2 Kings" WHERE BookID = 12;
UPDATE GNVVerses SET Book = "1 Chronicles" WHERE BookID = 13;
UPDATE GNVVerses SET Book = "2 Chronicles" WHERE BookID = 14;
UPDATE GNVVerses SET Book = "Ezra" WHERE BookID = 15;
UPDATE GNVVerses SET Book = "Nehemiah" WHERE BookID = 16;
UPDATE GNVVerses SET Book = "Esther" WHERE BookID = 17;
UPDATE GNVVerses SET Book = "Job" WHERE BookID = 18;
UPDATE GNVVerses SET Book = "Psalms" WHERE BookID = 19;
UPDATE GNVVerses SET Book = "Proverbs" WHERE BookID = 20;
UPDATE GNVVerses SET Book = "Ecclesiastes" WHERE BookID = 21;
UPDATE GNVVerses SET Book = "Song of Solomon" WHERE BookID = 22;
UPDATE GNVVerses SET Book = "Isaiah" WHERE BookID = 23;
UPDATE GNVVerses SET Book = "Jeremiah" WHERE BookID = 24;
UPDATE GNVVerses SET Book = "Lamentations" WHERE BookID = 25;
UPDATE GNVVerses SET Book = "Ezekiel" WHERE BookID = 26;
UPDATE GNVVerses SET Book = "Daniel" WHERE BookID = 27;
UPDATE GNVVerses SET Book = "Hosea" WHERE BookID = 28;
UPDATE GNVVerses SET Book = "Joel" WHERE BookID = 29;
UPDATE GNVVerses SET Book = "Amos" WHERE BookID = 30;
UPDATE GNVVerses SET Book = "Obadiah" WHERE BookID = 31;
UPDATE GNVVerses SET Book = "Jonah" WHERE BookID = 32;
UPDATE GNVVerses SET Book = "Micah" WHERE BookID = 33;
UPDATE GNVVerses SET Book = "Nahum" WHERE BookID = 34;
UPDATE GNVVerses SET Book = "Habakkuk" WHERE BookID = 35;
UPDATE GNVVerses SET Book = "Zephaniah" WHERE BookID = 36;
UPDATE GNVVerses SET Book = "Haggai" WHERE BookID = 37;
UPDATE GNVVerses SET Book = "Zechariah" WHERE BookID = 38;
UPDATE GNVVerses SET Book = "Malachi" WHERE BookID = 39;
UPDATE GNVVerses SET Book = "Matthew" WHERE BookID = 40;
UPDATE GNVVerses SET Book = "Mark" WHERE BookID = 41;
UPDATE GNVVerses SET Book = "Luke" WHERE BookID = 42;
UPDATE GNVVerses SET Book = "John" WHERE BookID = 43;
UPDATE GNVVerses SET Book = "Acts" WHERE BookID = 44;
UPDATE GNVVerses SET Book = "Romans" WHERE BookID = 45;
UPDATE GNVVerses SET Book = "1 Corinthians" WHERE BookID = 46;
UPDATE GNVVerses SET Book = "2 Corinthians" WHERE BookID = 47;
UPDATE GNVVerses SET Book = "Galatians" WHERE BookID = 48;
UPDATE GNVVerses SET Book = "Ephesians" WHERE BookID = 49;
UPDATE GNVVerses SET Book = "Philippians" WHERE BookID = 50;
UPDATE GNVVerses SET Book = "Colossians" WHERE BookID = 51;
UPDATE GNVVerses SET Book = "1 Thessalonians" WHERE BookID = 52;
UPDATE GNVVerses SET Book = "2 Thessalonians" WHERE BookID = 53;
UPDATE GNVVerses SET Book = "1 Timothy" WHERE BookID = 54;
UPDATE GNVVerses SET Book = "2 Timothy" WHERE BookID = 55;
UPDATE GNVVerses SET Book = "Titus" WHERE BookID = 56;
UPDATE GNVVerses SET Book = "Philemon" WHERE BookID = 57;
UPDATE GNVVerses SET Book = "Hebrews" WHERE BookID = 58;
UPDATE GNVVerses SET Book = "James" WHERE BookID = 59;
UPDATE GNVVerses SET Book = "1 Peter" WHERE BookID = 60;
UPDATE GNVVerses SET Book = "2 Peter" WHERE BookID = 61;
UPDATE GNVVerses SET Book = "1 John" WHERE BookID = 62;
UPDATE GNVVerses SET Book = "2 John" WHERE BookID = 63;
UPDATE GNVVerses SET Book = "3 John" WHERE BookID = 64;
UPDATE GNVVerses SET Book = "Jude" WHERE BookID = 65;
UPDATE GNVVerses SET Book = "Revelation" WHERE BookID = 66;