UPDATE JPSVerses SET BookID = 1, Book = "Genesis" WHERE Book = "GEN";
UPDATE JPSVerses SET BookID = 2, Book = "Exodus" WHERE Book = "EXO";
UPDATE JPSVerses SET BookID = 3, Book = "Leviticus" WHERE Book = "LEV";
UPDATE JPSVerses SET BookID = 4, Book = "Numbers" WHERE Book = "NUM";
UPDATE JPSVerses SET BookID = 5, Book = "Deuteronomy" WHERE Book = "DEU";
UPDATE JPSVerses SET BookID = 6, Book = "Joshua" WHERE Book = "JOS";
UPDATE JPSVerses SET BookID = 7, Book = "Judges" WHERE Book = "JDG";
UPDATE JPSVerses SET BookID = 8, Book = "Ruth" WHERE Book = "RUT";
UPDATE JPSVerses SET BookID = 9, Book = "1 Samuel" WHERE Book = "1SA";
UPDATE JPSVerses SET BookID = 10, Book = "2 Samuel" WHERE Book = "2SA";
UPDATE JPSVerses SET BookID = 11, Book = "1 Kings" WHERE Book = "1KI";
UPDATE JPSVerses SET BookID = 12, Book = "2 Kings" WHERE Book = "2KI";
UPDATE JPSVerses SET BookID = 13, Book = "1 Chronicles" WHERE Book = "1CH";
UPDATE JPSVerses SET BookID = 14, Book = "2 Chronicles" WHERE Book = "2CH";
UPDATE JPSVerses SET BookID = 15, Book = "Ezra" WHERE Book = "EZR";
UPDATE JPSVerses SET BookID = 16, Book = "Nehemiah" WHERE Book = "NEH";
UPDATE JPSVerses SET BookID = 17, Book = "Esther" WHERE Book = "EST";
UPDATE JPSVerses SET BookID = 18, Book = "Job" WHERE Book = "JOB";
UPDATE JPSVerses SET BookID = 19, Book = "Psalms" WHERE Book = "PSA";
UPDATE JPSVerses SET BookID = 20, Book = "Proverbs" WHERE Book = "PRO";
UPDATE JPSVerses SET BookID = 21, Book = "Ecclesiastes" WHERE Book = "ECC";
UPDATE JPSVerses SET BookID = 22, Book = "Song of Solomon" WHERE Book = "SNG";
UPDATE JPSVerses SET BookID = 23, Book = "Isaiah" WHERE Book = "ISA";
UPDATE JPSVerses SET BookID = 24, Book = "Jeremiah" WHERE Book = "JER";
UPDATE JPSVerses SET BookID = 25, Book = "Lamentations" WHERE Book = "LAM";
UPDATE JPSVerses SET BookID = 26, Book = "Ezekiel" WHERE Book = "EZK";
UPDATE JPSVerses SET BookID = 27, Book = "Daniel" WHERE Book = "DAN";
UPDATE JPSVerses SET BookID = 28, Book = "Hosea" WHERE Book = "HOS";
UPDATE JPSVerses SET BookID = 29, Book = "Joel" WHERE Book = "JOL";
UPDATE JPSVerses SET BookID = 30, Book = "Amos" WHERE Book = "AMO";
UPDATE JPSVerses SET BookID = 31, Book = "Obadiah" WHERE Book = "OBA";
UPDATE JPSVerses SET BookID = 32, Book = "Jonah" WHERE Book = "JON";
UPDATE JPSVerses SET BookID = 33, Book = "Micah" WHERE Book = "MIC";
UPDATE JPSVerses SET BookID = 34, Book = "Nahum" WHERE Book = "NAM";
UPDATE JPSVerses SET BookID = 35, Book = "Habakkuk" WHERE Book = "HAB";
UPDATE JPSVerses SET BookID = 36, Book = "Zephaniah" WHERE Book = "ZEP";
UPDATE JPSVerses SET BookID = 37, Book = "Haggai" WHERE Book = "HAG";
UPDATE JPSVerses SET BookID = 38, Book = "Zechariah" WHERE Book = "ZEC";
UPDATE JPSVerses SET BookID = 39, Book = "Malachi" WHERE Book = "MAL";