UPDATE WEYVerses SET BookID = 1 WHERE Book = "Matthew";
UPDATE WEYVerses SET BookID = 2 WHERE Book = "Mark";
UPDATE WEYVerses SET BookID = 3 WHERE Book = "Luke";
UPDATE WEYVerses SET BookID = 4 WHERE Book = "John";
UPDATE WEYVerses SET BookID = 5 WHERE Book = "Acts";
UPDATE WEYVerses SET BookID = 6 WHERE Book = "Romans";
UPDATE WEYVerses SET BookID = 7 WHERE Book = "1 Corinthians";
UPDATE WEYVerses SET BookID = 8 WHERE Book = "2 Corinthians";
UPDATE WEYVerses SET BookID = 9 WHERE Book = "Galatians";
UPDATE WEYVerses SET BookID = 10 WHERE Book = "Ephesians";
UPDATE WEYVerses SET BookID = 11 WHERE Book = "Philippians";
UPDATE WEYVerses SET BookID = 12 WHERE Book = "Colossians";
UPDATE WEYVerses SET BookID = 13 WHERE Book = "1 Thessalonians";
UPDATE WEYVerses SET BookID = 14 WHERE Book = "2 Thessalonians";
UPDATE WEYVerses SET BookID = 15 WHERE Book = "1 Timothy";
UPDATE WEYVerses SET BookID = 16 WHERE Book = "2 Timothy";
UPDATE WEYVerses SET BookID = 17 WHERE Book = "Titus";
UPDATE WEYVerses SET BookID = 18 WHERE Book = "Philemon";
UPDATE WEYVerses SET BookID = 19 WHERE Book = "Hebrews";
UPDATE WEYVerses SET BookID = 20 WHERE Book = "James";
UPDATE WEYVerses SET BookID = 21 WHERE Book = "1 Peter";
UPDATE WEYVerses SET BookID = 22 WHERE Book = "2 Peter";
UPDATE WEYVerses SET BookID = 23 WHERE Book = "1 John";
UPDATE WEYVerses SET BookID = 24 WHERE Book = "2 John";
UPDATE WEYVerses SET BookID = 25 WHERE Book = "3 John";
UPDATE WEYVerses SET BookID = 26 WHERE Book = "Jude";
UPDATE WEYVerses SET BookID = 27 WHERE Book = "Revelation";