UPDATE ASVVerses SET BookID = 1, Book = "Genesis" WHERE Book = "GEN";
UPDATE ASVVerses SET BookID = 2, Book = "Exodus" WHERE Book = "EXO";
UPDATE ASVVerses SET BookID = 3, Book = "Leviticus" WHERE Book = "LEV";
UPDATE ASVVerses SET BookID = 4, Book = "Numbers" WHERE Book = "NUM";
UPDATE ASVVerses SET BookID = 5, Book = "Deuteronomy" WHERE Book = "DEU";
UPDATE ASVVerses SET BookID = 6, Book = "Joshua" WHERE Book = "JOS";
UPDATE ASVVerses SET BookID = 7, Book = "Judges" WHERE Book = "JDG";
UPDATE ASVVerses SET BookID = 8, Book = "Ruth" WHERE Book = "RUT";
UPDATE ASVVerses SET BookID = 9, Book = "1 Samuel" WHERE Book = "1SA";
UPDATE ASVVerses SET BookID = 10, Book = "2 Samuel" WHERE Book = "2SA";
UPDATE ASVVerses SET BookID = 11, Book = "1 Kings" WHERE Book = "1KI";
UPDATE ASVVerses SET BookID = 12, Book = "2 Kings" WHERE Book = "2KI";
UPDATE ASVVerses SET BookID = 13, Book = "1 Chronicles" WHERE Book = "1CH";
UPDATE ASVVerses SET BookID = 14, Book = "2 Chronicles" WHERE Book = "2CH";
UPDATE ASVVerses SET BookID = 15, Book = "Ezra" WHERE Book = "EZR";
UPDATE ASVVerses SET BookID = 16, Book = "Nehemiah" WHERE Book = "NEH";
UPDATE ASVVerses SET BookID = 17, Book = "Esther" WHERE Book = "EST";
UPDATE ASVVerses SET BookID = 18, Book = "Job" WHERE Book = "JOB";
UPDATE ASVVerses SET BookID = 19, Book = "Psalms" WHERE Book = "PSA";
UPDATE ASVVerses SET BookID = 20, Book = "Proverbs" WHERE Book = "PRO";
UPDATE ASVVerses SET BookID = 21, Book = "Ecclesiastes" WHERE Book = "ECC";
UPDATE ASVVerses SET BookID = 22, Book = "Song of Solomon" WHERE Book = "SNG";
UPDATE ASVVerses SET BookID = 23, Book = "Isaiah" WHERE Book = "ISA";
UPDATE ASVVerses SET BookID = 24, Book = "Jeremiah" WHERE Book = "JER";
UPDATE ASVVerses SET BookID = 25, Book = "LamenASVions" WHERE Book = "LAM";
UPDATE ASVVerses SET BookID = 26, Book = "Ezekiel" WHERE Book = "EZK";
UPDATE ASVVerses SET BookID = 27, Book = "Daniel" WHERE Book = "DAN";
UPDATE ASVVerses SET BookID = 28, Book = "Hosea" WHERE Book = "HOS";
UPDATE ASVVerses SET BookID = 29, Book = "Joel" WHERE Book = "JOL";
UPDATE ASVVerses SET BookID = 30, Book = "Amos" WHERE Book = "AMO";
UPDATE ASVVerses SET BookID = 31, Book = "Obadiah" WHERE Book = "OBA";
UPDATE ASVVerses SET BookID = 32, Book = "Jonah" WHERE Book = "JON";
UPDATE ASVVerses SET BookID = 33, Book = "Micah" WHERE Book = "MIC";
UPDATE ASVVerses SET BookID = 34, Book = "Nahum" WHERE Book = "NAM";
UPDATE ASVVerses SET BookID = 35, Book = "Habakkuk" WHERE Book = "HAB";
UPDATE ASVVerses SET BookID = 36, Book = "Zephaniah" WHERE Book = "ZEP";
UPDATE ASVVerses SET BookID = 37, Book = "Haggai" WHERE Book = "HAG";
UPDATE ASVVerses SET BookID = 38, Book = "Zechariah" WHERE Book = "ZEC";
UPDATE ASVVerses SET BookID = 39, Book = "Malachi" WHERE Book = "MAL";
UPDATE ASVVerses SET BookID = 40, Book = "Matthew" WHERE Book = "MAT";
UPDATE ASVVerses SET BookID = 41, Book = "Mark" WHERE Book = "MRK";
UPDATE ASVVerses SET BookID = 42, Book = "Luke" WHERE Book = "LUK";
UPDATE ASVVerses SET BookID = 43, Book = "John" WHERE Book = "JHN";
UPDATE ASVVerses SET BookID = 44, Book = "Acts" WHERE Book = "ACT";
UPDATE ASVVerses SET BookID = 45, Book = "Romans" WHERE Book = "ROM";
UPDATE ASVVerses SET BookID = 46, Book = "1 Corinthians" WHERE Book = "1CO";
UPDATE ASVVerses SET BookID = 47, Book = "2 Corinthians" WHERE Book = "2CO";
UPDATE ASVVerses SET BookID = 48, Book = "Galatians" WHERE Book = "GAL";
UPDATE ASVVerses SET BookID = 49, Book = "Ephesians" WHERE Book = "EPH";
UPDATE ASVVerses SET BookID = 50, Book = "Philippians" WHERE Book = "PHP";
UPDATE ASVVerses SET BookID = 51, Book = "Colossians" WHERE Book = "COL";
UPDATE ASVVerses SET BookID = 52, Book = "1 Thessalonians" WHERE Book = "1TH";
UPDATE ASVVerses SET BookID = 53, Book = "2 Thessalonians" WHERE Book = "2TH";
UPDATE ASVVerses SET BookID = 54, Book = "1 Timothy" WHERE Book = "1TI";
UPDATE ASVVerses SET BookID = 55, Book = "2 Timothy" WHERE Book = "2TI";
UPDATE ASVVerses SET BookID = 56, Book = "Titus" WHERE Book = "TIT";
UPDATE ASVVerses SET BookID = 57, Book = "Philemon" WHERE Book = "PHM";
UPDATE ASVVerses SET BookID = 58, Book = "Hebrews" WHERE Book = "HEB";
UPDATE ASVVerses SET BookID = 59, Book = "James" WHERE Book = "JAS";
UPDATE ASVVerses SET BookID = 60, Book = "1 Peter" WHERE Book = "1PE";
UPDATE ASVVerses SET BookID = 61, Book = "2 Peter" WHERE Book = "2PE";
UPDATE ASVVerses SET BookID = 62, Book = "1 John" WHERE Book = "1JN";
UPDATE ASVVerses SET BookID = 63, Book = "2 John" WHERE Book = "2JN";
UPDATE ASVVerses SET BookID = 64, Book = "3 John" WHERE Book = "3JN";
UPDATE ASVVerses SET BookID = 65, Book = "Jude" WHERE Book = "JUD";
UPDATE ASVVerses SET BookID = 66, Book = "Revelation" WHERE Book = "REV";