UPDATE DREVerses SET BookID = 1, Book = "Matthew" WHERE Book = "MAT";
UPDATE DREVerses SET BookID = 2, Book = "Mark" WHERE Book = "MRK";
UPDATE DREVerses SET BookID = 3, Book = "Luke" WHERE Book = "LUK";
UPDATE DREVerses SET BookID = 4, Book = "John" WHERE Book = "JHN";
UPDATE DREVerses SET BookID = 5, Book = "Acts" WHERE Book = "ACT";
UPDATE DREVerses SET BookID = 6, Book = "Romans" WHERE Book = "ROM";
UPDATE DREVerses SET BookID = 7, Book = "1 Corinthians" WHERE Book = "1CO";
UPDATE DREVerses SET BookID = 8, Book = "2 Corinthians" WHERE Book = "2CO";
UPDATE DREVerses SET BookID = 9, Book = "Galatians" WHERE Book = "GAL";
UPDATE DREVerses SET BookID = 10, Book = "Ephesians" WHERE Book = "EPH";
UPDATE DREVerses SET BookID = 11, Book = "Philippians" WHERE Book = "PHP";
UPDATE DREVerses SET BookID = 12, Book = "Colossians" WHERE Book = "COL";
UPDATE DREVerses SET BookID = 13, Book = "1 Thessalonians" WHERE Book = "1TH";
UPDATE DREVerses SET BookID = 14, Book = "2 Thessalonians" WHERE Book = "2TH";
UPDATE DREVerses SET BookID = 15, Book = "1 Timothy" WHERE Book = "1TI";
UPDATE DREVerses SET BookID = 16, Book = "2 Timothy" WHERE Book = "2TI";
UPDATE DREVerses SET BookID = 17, Book = "Titus" WHERE Book = "TIT";
UPDATE DREVerses SET BookID = 18, Book = "Philemon" WHERE Book = "PHM";
UPDATE DREVerses SET BookID = 19, Book = "Hebrews" WHERE Book = "HEB";
UPDATE DREVerses SET BookID = 20, Book = "James" WHERE Book = "JAS";
UPDATE DREVerses SET BookID = 21, Book = "1 Peter" WHERE Book = "1PE";
UPDATE DREVerses SET BookID = 22, Book = "2 Peter" WHERE Book = "2PE";
UPDATE DREVerses SET BookID = 23, Book = "1 John" WHERE Book = "1JN";
UPDATE DREVerses SET BookID = 24, Book = "2 John" WHERE Book = "2JN";
UPDATE DREVerses SET BookID = 25, Book = "3 John" WHERE Book = "3JN";
UPDATE DREVerses SET BookID = 26, Book = "Jude" WHERE Book = "JUD";
UPDATE DREVerses SET BookID = 27, Book = "Revelation" WHERE Book = "REV";