UPDATE DRVVerses SET BookID = 1 WHERE Book = "Genesis";
UPDATE DRVVerses SET BookID = 2 WHERE Book = "Exodus";
UPDATE DRVVerses SET BookID = 3 WHERE Book = "Leviticus";
UPDATE DRVVerses SET BookID = 4 WHERE Book = "Numbers";
UPDATE DRVVerses SET BookID = 5 WHERE Book = "Deuteronomy";
UPDATE DRVVerses SET BookID = 6 WHERE Book = "Joshua";
UPDATE DRVVerses SET BookID = 7 WHERE Book = "Judges";
UPDATE DRVVerses SET BookID = 8 WHERE Book = "RUTH";
UPDATE DRVVerses SET BookID = 9 WHERE Book = "1 Samuel";
UPDATE DRVVerses SET BookID = 10 WHERE Book = "2 Samuel";
UPDATE DRVVerses SET BookID = 11 WHERE Book = "1 Kings";
UPDATE DRVVerses SET BookID = 12 WHERE Book = "2 Kings";
UPDATE DRVVerses SET BookID = 13 WHERE Book = "1 Chronicles";
UPDATE DRVVerses SET BookID = 14 WHERE Book = "2 Chronicles";
UPDATE DRVVerses SET BookID = 15 WHERE Book = "Ezra";
UPDATE DRVVerses SET BookID = 16 WHERE Book = "Nehemiah";
UPDATE DRVVerses SET BookID = 17 WHERE Book = "Esther";
UPDATE DRVVerses SET BookID = 18 WHERE Book = "Job";
UPDATE DRVVerses SET BookID = 19 WHERE Book = "Psalms";
UPDATE DRVVerses SET BookID = 20 WHERE Book = "Proverbs";
UPDATE DRVVerses SET BookID = 21 WHERE Book = "Ecclesiastes";
UPDATE DRVVerses SET BookID = 22 WHERE Book = "Song of Solomon";
UPDATE DRVVerses SET BookID = 23 WHERE Book = "Isaiah";
UPDATE DRVVerses SET BookID = 24 WHERE Book = "Jeremiah";
UPDATE DRVVerses SET BookID = 25 WHERE Book = "Lamentations";
UPDATE DRVVerses SET BookID = 26 WHERE Book = "Ezekiel";
UPDATE DRVVerses SET BookID = 27 WHERE Book = "Daniel";
UPDATE DRVVerses SET BookID = 28 WHERE Book = "Hosea";
UPDATE DRVVerses SET BookID = 29 WHERE Book = "Joel";
UPDATE DRVVerses SET BookID = 30 WHERE Book = "Amos";
UPDATE DRVVerses SET BookID = 31 WHERE Book = "Obadiah";
UPDATE DRVVerses SET BookID = 32 WHERE Book = "Jonah";
UPDATE DRVVerses SET BookID = 33 WHERE Book = "Micah";
UPDATE DRVVerses SET BookID = 34 WHERE Book = "Nahum";
UPDATE DRVVerses SET BookID = 35 WHERE Book = "Habakkuk";
UPDATE DRVVerses SET BookID = 36 WHERE Book = "Zephaniah";
UPDATE DRVVerses SET BookID = 37 WHERE Book = "Haggai";
UPDATE DRVVerses SET BookID = 38 WHERE Book = "Zechariah";
UPDATE DRVVerses SET BookID = 39 WHERE Book = "Malachi";
UPDATE DRVVerses SET BookID = 40 WHERE Book = "Tobit";
UPDATE DRVVerses SET BookID = 41 WHERE Book = "Judith";
UPDATE DRVVerses SET BookID = 42 WHERE Book = "Wisdom of Solomon";
UPDATE DRVVerses SET BookID = 43 WHERE Book = "Sirach";
UPDATE DRVVerses SET BookID = 44 WHERE Book = "Baruch";
UPDATE DRVVerses SET BookID = 45 WHERE Book = "1 Maccabees";
UPDATE DRVVerses SET BookID = 46 WHERE Book = "2 Maccabees";
UPDATE DRVVerses SET BookID = 47 WHERE Book = "Matthew";
UPDATE DRVVerses SET BookID = 48 WHERE Book = "Mark";
UPDATE DRVVerses SET BookID = 49 WHERE Book = "Luke";
UPDATE DRVVerses SET BookID = 50 WHERE Book = "John";
UPDATE DRVVerses SET BookID = 51 WHERE Book = "Acts";
UPDATE DRVVerses SET BookID = 52 WHERE Book = "Romans";
UPDATE DRVVerses SET BookID = 53 WHERE Book = "1 Corinthians";
UPDATE DRVVerses SET BookID = 54 WHERE Book = "2 Corinthians";
UPDATE DRVVerses SET BookID = 55 WHERE Book = "Galatians";
UPDATE DRVVerses SET BookID = 56 WHERE Book = "Ephesians";
UPDATE DRVVerses SET BookID = 57 WHERE Book = "Philippians";
UPDATE DRVVerses SET BookID = 58 WHERE Book = "Colossians";
UPDATE DRVVerses SET BookID = 59 WHERE Book = "1 Thessalonians";
UPDATE DRVVerses SET BookID = 60 WHERE Book = "2 Thessalonians";
UPDATE DRVVerses SET BookID = 61 WHERE Book = "1 Timothy";
UPDATE DRVVerses SET BookID = 62 WHERE Book = "2 Timothy";
UPDATE DRVVerses SET BookID = 63 WHERE Book = "Titus";
UPDATE DRVVerses SET BookID = 64 WHERE Book = "Philemon";
UPDATE DRVVerses SET BookID = 65 WHERE Book = "Hebrews";
UPDATE DRVVerses SET BookID = 66 WHERE Book = "James";
UPDATE DRVVerses SET BookID = 67 WHERE Book = "1 Peter";
UPDATE DRVVerses SET BookID = 68 WHERE Book = "2 Peter";
UPDATE DRVVerses SET BookID = 69 WHERE Book = "1 John";
UPDATE DRVVerses SET BookID = 70 WHERE Book = "2 John";
UPDATE DRVVerses SET BookID = 71 WHERE Book = "3 John";
UPDATE DRVVerses SET BookID = 72 WHERE Book = "Jude";
UPDATE DRVVerses SET BookID = 73 WHERE Book = "Revelation";