ALTER TABLE BBEVerses RENAME COLUMN field1 TO BookID;
ALTER TABLE BBEVerses RENAME COLUMN field2 TO ChapterNumber;
ALTER TABLE BBEVerses RENAME COLUMN field3 TO JesusQuote;
ALTER TABLE BBEVerses RENAME COLUMN field4 TO ParagraphNumber;
ALTER TABLE BBEVerses RENAME COLUMN field5 TO VerseID;
ALTER TABLE BBEVerses RENAME COLUMN field6 TO VerseNumber;
ALTER TABLE BBEVerses RENAME COLUMN field7 TO VerseText;
ALTER TABLE BBEVerses ADD COLUMN VersionID INTEGER DEFAULT 0;
ALTER TABLE BBEVerses ADD COLUMN VolumeID INTEGER DEFAULT 0;
UPDATE BBEVerses SET VersionID = 3;


