BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "TYNBooks" (
	"BookID"	INTEGER NOT NULL DEFAULT 0 UNIQUE,
	"Book"	TEXT NOT NULL DEFAULT '',
	"Abreviation"	TEXT NOT NULL DEFAULT '',
	"Chapters"	INTEGER NOT NULL DEFAULT 0,
	PRIMARY KEY("BookID" AUTOINCREMENT)
);
INSERT INTO "TYNBooks" VALUES (1,'Genesis','GEN',50);
INSERT INTO "TYNBooks" VALUES (2,'Exodus','EXO',40);
INSERT INTO "TYNBooks" VALUES (3,'Leviticus','LEV',27);
INSERT INTO "TYNBooks" VALUES (4,'Numbers','NUM',36);
INSERT INTO "TYNBooks" VALUES (5,'Deuteronomy','DEU',34);
INSERT INTO "TYNBooks" VALUES (6,'Jonah','JON',4);
INSERT INTO "TYNBooks" VALUES (7,'Matthew','MAT',28);
INSERT INTO "TYNBooks" VALUES (8,'Mark','MRK',16);
INSERT INTO "TYNBooks" VALUES (9,'Luke','LUK',24);
INSERT INTO "TYNBooks" VALUES (10,'John','JHN',21);
INSERT INTO "TYNBooks" VALUES (11,'Acts','ACT',28);
INSERT INTO "TYNBooks" VALUES (12,'Romans','ROM',16);
INSERT INTO "TYNBooks" VALUES (13,'1 Corinthians','1CO',16);
INSERT INTO "TYNBooks" VALUES (14,'2 Corinthians','2CO',13);
INSERT INTO "TYNBooks" VALUES (15,'Galatians','GAL',6);
INSERT INTO "TYNBooks" VALUES (16,'Ephesians','EPH',6);
INSERT INTO "TYNBooks" VALUES (17,'Philippians','PHP',4);
INSERT INTO "TYNBooks" VALUES (18,'Colossians','COL',4);
INSERT INTO "TYNBooks" VALUES (19,'1 Thessalonians','1TH',5);
INSERT INTO "TYNBooks" VALUES (20,'2 Thessalonians','2TH',3);
INSERT INTO "TYNBooks" VALUES (21,'1 Timothy','1TI',6);
INSERT INTO "TYNBooks" VALUES (22,'2 Timothy','2TI',4);
INSERT INTO "TYNBooks" VALUES (23,'Titus','TIT',3);
INSERT INTO "TYNBooks" VALUES (24,'Philemon','PHM',4);
INSERT INTO "TYNBooks" VALUES (25,'Hebrews','HEB',13);
INSERT INTO "TYNBooks" VALUES (26,'James','JAS',5);
INSERT INTO "TYNBooks" VALUES (27,'1 Peter','1PE',5);
INSERT INTO "TYNBooks" VALUES (28,'2 Peter','2PE',3);
INSERT INTO "TYNBooks" VALUES (29,'1 John','1JN',5);
INSERT INTO "TYNBooks" VALUES (30,'2 John','2JN',1);
INSERT INTO "TYNBooks" VALUES (31,'3 John','3JN',1);
INSERT INTO "TYNBooks" VALUES (32,'Jude','JUD',1);
INSERT INTO "TYNBooks" VALUES (33,'Revelation','REV',22);
COMMIT;
