BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "JPSBooks" (
	"BookID"	INTEGER NOT NULL DEFAULT 0 UNIQUE,
	"Book"	TEXT NOT NULL DEFAULT '',
	"Abreviation"	TEXT NOT NULL DEFAULT '',
	"Chapters"	INTEGER NOT NULL DEFAULT 0,
	PRIMARY KEY("BookID" AUTOINCREMENT)
);
INSERT INTO "JPSBooks" VALUES (1,'Genesis','GEN',50);
INSERT INTO "JPSBooks" VALUES (2,'Exodus','EXO',40);
INSERT INTO "JPSBooks" VALUES (3,'Leviticus','LEV',27);
INSERT INTO "JPSBooks" VALUES (4,'Numbers','NUM',36);
INSERT INTO "JPSBooks" VALUES (5,'Deuteronomy','DEU',34);
INSERT INTO "JPSBooks" VALUES (6,'Joshua','JOS',24);
INSERT INTO "JPSBooks" VALUES (7,'Judges','JDG',21);
INSERT INTO "JPSBooks" VALUES (8,'1 Samuel','1SA',31);
INSERT INTO "JPSBooks" VALUES (9,'2 Samuel','2SA',24);
INSERT INTO "JPSBooks" VALUES (10,'1 Kings','1KI',22);
INSERT INTO "JPSBooks" VALUES (11,'2 Kings','2KI',25);
INSERT INTO "JPSBooks" VALUES (12,'Isaiah','ISA',66);
INSERT INTO "JPSBooks" VALUES (13,'Jeremiah','JER',52);
INSERT INTO "JPSBooks" VALUES (14,'Ezekiel','EZK',48);
INSERT INTO "JPSBooks" VALUES (15,'Hosea','HOS',14);
INSERT INTO "JPSBooks" VALUES (16,'Joel','JOL',3);
INSERT INTO "JPSBooks" VALUES (17,'Amos','AMO',9);
INSERT INTO "JPSBooks" VALUES (18,'Obadiah','OBA',1);
INSERT INTO "JPSBooks" VALUES (19,'Jonah','JON',4);
INSERT INTO "JPSBooks" VALUES (20,'Micah','MIC',7);
INSERT INTO "JPSBooks" VALUES (21,'Nahum','NAM',3);
INSERT INTO "JPSBooks" VALUES (22,'Habakkuk','HAB',3);
INSERT INTO "JPSBooks" VALUES (23,'Zephaniah','ZEP',3);
INSERT INTO "JPSBooks" VALUES (24,'Haggai','HAG',2);
INSERT INTO "JPSBooks" VALUES (25,'Zechariah','ZEC',14);
INSERT INTO "JPSBooks" VALUES (26,'Malachi','MAL',4);
INSERT INTO "JPSBooks" VALUES (27,'Psalms','PSA',150);
INSERT INTO "JPSBooks" VALUES (28,'Proverbs','PRO',31);
INSERT INTO "JPSBooks" VALUES (29,'Job','JOB',42);
INSERT INTO "JPSBooks" VALUES (30,'Song of Solomon','SNG',8);
INSERT INTO "JPSBooks" VALUES (31,'Lamentations','LAM',5);
INSERT INTO "JPSBooks" VALUES (32,'Ecclesiastes','ECC',12);
INSERT INTO "JPSBooks" VALUES (33,'Esther','EST',10);
INSERT INTO "JPSBooks" VALUES (34,'Ruth','RUT',4);
INSERT INTO "JPSBooks" VALUES (35,'Daniel','DAN',12);
INSERT INTO "JPSBooks" VALUES (36,'Ezra','EZR',10);
INSERT INTO "JPSBooks" VALUES (37,'Nehemiah','NEH',13);
INSERT INTO "JPSBooks" VALUES (38,'1 Chronicles','1CH',29);
INSERT INTO "JPSBooks" VALUES (39,'2 Chronicles','2CH',36);
COMMIT;
