BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "73-FormalBooks" (
	"BookID"	INTEGER NOT NULL DEFAULT 0 UNIQUE,
	"Book"	TEXT NOT NULL DEFAULT '',
	"Abreviation"	TEXT NOT NULL DEFAULT '',
	"Chapters"	INTEGER NOT NULL DEFAULT 0,
	PRIMARY KEY("BookID" AUTOINCREMENT)
);
INSERT INTO "73-FormalBooks" VALUES (1,'Genesis','GEN',50);
INSERT INTO "73-FormalBooks" VALUES (2,'Exodus','EXO',40);
INSERT INTO "73-FormalBooks" VALUES (3,'Leviticus','LEV',27);
INSERT INTO "73-FormalBooks" VALUES (4,'Numbers','NUM',36);
INSERT INTO "73-FormalBooks" VALUES (5,'Deuteronomy','DEU',34);
INSERT INTO "73-FormalBooks" VALUES (6,'Joshua','JOS',24);
INSERT INTO "73-FormalBooks" VALUES (7,'Judges','JDG',21);
INSERT INTO "73-FormalBooks" VALUES (8,'Ruth','RUT',4);
INSERT INTO "73-FormalBooks" VALUES (9,'First Samuel','1SA',31);
INSERT INTO "73-FormalBooks" VALUES (10,'Second Samuel','2SA',24);
INSERT INTO "73-FormalBooks" VALUES (11,'First Kings','1KI',22);
INSERT INTO "73-FormalBooks" VALUES (12,'Second Kings','2KI',25);
INSERT INTO "73-FormalBooks" VALUES (13,'First Chronicles','1CH',29);
INSERT INTO "73-FormalBooks" VALUES (14,'Second Chronicles','2CH',36);
INSERT INTO "73-FormalBooks" VALUES (15,'Ezra','EZR',10);
INSERT INTO "73-FormalBooks" VALUES (16,'Nehemiah','NEH',13);
INSERT INTO "73-FormalBooks" VALUES (17,'Esther','EST',16);
INSERT INTO "73-FormalBooks" VALUES (18,'Job','JOB',42);
INSERT INTO "73-FormalBooks" VALUES (19,'Psalms','PSA',150);
INSERT INTO "73-FormalBooks" VALUES (20,'Proverbs','PRO',31);
INSERT INTO "73-FormalBooks" VALUES (21,'Ecclesiastes','ECC',12);
INSERT INTO "73-FormalBooks" VALUES (22,'Song of Solomon','SNG',8);
INSERT INTO "73-FormalBooks" VALUES (23,'Isaiah','ISA',66);
INSERT INTO "73-FormalBooks" VALUES (24,'Jeremiah','JER',52);
INSERT INTO "73-FormalBooks" VALUES (25,'Lamentations','LAM',5);
INSERT INTO "73-FormalBooks" VALUES (26,'Ezekiel','EZK',48);
INSERT INTO "73-FormalBooks" VALUES (27,'Daniel','DAN',14);
INSERT INTO "73-FormalBooks" VALUES (28,'Hosea','HOS',14);
INSERT INTO "73-FormalBooks" VALUES (29,'Joel','JOL',3);
INSERT INTO "73-FormalBooks" VALUES (30,'Amos','AMO',9);
INSERT INTO "73-FormalBooks" VALUES (31,'Obadiah','OBA',1);
INSERT INTO "73-FormalBooks" VALUES (32,'Jonah','JON',4);
INSERT INTO "73-FormalBooks" VALUES (33,'Micah','MIC',7);
INSERT INTO "73-FormalBooks" VALUES (34,'Nahum','NAM',3);
INSERT INTO "73-FormalBooks" VALUES (35,'Habakkuk','HAB',3);
INSERT INTO "73-FormalBooks" VALUES (36,'Zephaniah','ZEP',3);
INSERT INTO "73-FormalBooks" VALUES (37,'Haggai','HAG',2);
INSERT INTO "73-FormalBooks" VALUES (38,'Zechariah','ZEC',14);
INSERT INTO "73-FormalBooks" VALUES (39,'Malachi','MAL',4);
INSERT INTO "73-FormalBooks" VALUES (40,'Tobit','TOB',14);
INSERT INTO "73-FormalBooks" VALUES (41,'Judith','JDT',16);
INSERT INTO "73-FormalBooks" VALUES (42,'Wisdom of Solomon','WIS',19);
INSERT INTO "73-FormalBooks" VALUES (43,'Sirach','SIR',51);
INSERT INTO "73-FormalBooks" VALUES (44,'Baruch','BAR',6);
INSERT INTO "73-FormalBooks" VALUES (45,'First Maccabees','1MA',16);
INSERT INTO "73-FormalBooks" VALUES (46,'Second Maccabees','2MA',15);
INSERT INTO "73-FormalBooks" VALUES (47,'Matthew','MAT',28);
INSERT INTO "73-FormalBooks" VALUES (48,'Mark','MRK',16);
INSERT INTO "73-FormalBooks" VALUES (49,'Luke','LUK',24);
INSERT INTO "73-FormalBooks" VALUES (50,'John','JHN',21);
INSERT INTO "73-FormalBooks" VALUES (51,'Acts','ACT',28);
INSERT INTO "73-FormalBooks" VALUES (52,'Romans','ROM',16);
INSERT INTO "73-FormalBooks" VALUES (53,'First Corinthians','1CO',16);
INSERT INTO "73-FormalBooks" VALUES (54,'Second Corinthians','2CO',13);
INSERT INTO "73-FormalBooks" VALUES (55,'Galatians','GAL',6);
INSERT INTO "73-FormalBooks" VALUES (56,'Ephesians','EPH',6);
INSERT INTO "73-FormalBooks" VALUES (57,'Philippians','PHP',4);
INSERT INTO "73-FormalBooks" VALUES (58,'Colossians','COL',4);
INSERT INTO "73-FormalBooks" VALUES (59,'First Thessalonians','1TH',5);
INSERT INTO "73-FormalBooks" VALUES (60,'Second Thessalonians','2TH',3);
INSERT INTO "73-FormalBooks" VALUES (61,'First Timothy','1TI',6);
INSERT INTO "73-FormalBooks" VALUES (62,'Second Timothy','2TI',4);
INSERT INTO "73-FormalBooks" VALUES (63,'Titus','TIT',3);
INSERT INTO "73-FormalBooks" VALUES (64,'Philemon','PHM',1);
INSERT INTO "73-FormalBooks" VALUES (65,'Hebrews','HEB',13);
INSERT INTO "73-FormalBooks" VALUES (66,'James','JAS',5);
INSERT INTO "73-FormalBooks" VALUES (67,'First Peter','1PE',5);
INSERT INTO "73-FormalBooks" VALUES (68,'Second Peter','2PE',3);
INSERT INTO "73-FormalBooks" VALUES (69,'First John','1JN',5);
INSERT INTO "73-FormalBooks" VALUES (70,'Second John','2JN',1);
INSERT INTO "73-FormalBooks" VALUES (71,'Third John','3JN',1);
INSERT INTO "73-FormalBooks" VALUES (72,'Jude','JUD',1);
INSERT INTO "73-FormalBooks" VALUES (73,'Revelation','REV',22);
COMMIT;
