CREATE TABLE IF NOT EXISTS "ASVVerses" (
	"VerseID"	INTEGER NOT NULL DEFAULT 0 UNIQUE,
	"BookID"	INTEGER NOT NULL DEFAULT 0,
	"ChapterNumber"	INTEGER NOT NULL DEFAULT 0,
	"VerseNumber"	INTEGER NOT NULL DEFAULT 0,
	"VerseText"	TEXT NOT NULL DEFAULT '',
	"JesusQuote"	INTEGER NOT NULL DEFAULT 0,
	"ParagraphNumber"	INTEGER NOT NULL DEFAULT 0,
	"VersionID"	INTEGER NOT NULL DEFAULT 0,
	"VolumeID"	INTEGER NOT NULL DEFAULT 0,
	PRIMARY KEY("VerseID" AUTOINCREMENT)
);