CREATE TABLE "AAAVersions" (
	"VersionID"	INTEGER NOT NULL DEFAULT 0 UNIQUE,
	"Abreviation"	TEXT NOT NULL DEFAULT '',
	"Title"	TEXT NOT NULL DEFAULT '',
	"Authors"	TEXT NOT NULL DEFAULT '',
	"History"	TEXT NOT NULL DEFAULT '',
	"WikiLink"	TEXT NOT NULL DEFAULT '',
	"Copyright"	TEXT NOT NULL DEFAULT 'Public Domain',
	"VerseCount"	INTEGER NOT NULL DEFAULT 0,
	"Available"	INTEGER NOT NULL DEFAULT 0,
	PRIMARY KEY("VersionID" AUTOINCREMENT)
);