CREATE TABLE "AFRVerses" (
	"VerseID"	INTEGER NOT NULL DEFAULT 0 UNIQUE,
	"BookID"	INTEGER NOT NULL DEFAULT 0,
	"Book"	TEXT NOT NULL DEFAULT '',
	"ChapterNumber"	INTEGER NOT NULL DEFAULT 0,
	"VerseNumber"	INTEGER NOT NULL DEFAULT 0,
	"VerseText"	TEXT NOT NULL DEFAULT '',
	"JesusQuote"	INTEGER NOT NULL DEFAULT 0,
	"ParagraphNumber"	INTEGER NOT NULL DEFAULT 0,
	"VersionID"	INTEGER NOT NULL DEFAULT 0,
	"VolumeID"	INTEGER NOT NULL DEFAULT 0,
	PRIMARY KEY("VerseID" AUTOINCREMENT)
);