CREATE TABLE "AAAVersions" (
	`VersionID`	INTEGER NOT NULL DEFAULT 0 UNIQUE,
	`Title`	TEXT NOT NULL DEFAULT '',
	`CopyrightID`	INTEGER NOT NULL DEFAULT 0,
	`Copyright`	TEXT NOT NULL DEFAULT 'Public Domain',
	`LanguageID`	INTEGER NOT NULL DEFAULT 0,
	`Language`	TEXT NOT NULL DEFAULT '',
	`Abreviation`	TEXT NOT NULL DEFAULT '',
	`Authors`	TEXT NOT NULL DEFAULT '',
	`History`	TEXT NOT NULL DEFAULT '',
	`Links`	TEXT NOT NULL DEFAULT '',
	`VerseCount`	INTEGER NOT NULL DEFAULT 0,
	`Strongs`	INTEGER NOT NULL DEFAULT 0,
	`Searchable`	INTEGER NOT NULL DEFAULT 0,
	`RedLetter`	INTEGER NOT NULL DEFAULT 0,
	`Status`	INTEGER NOT NULL DEFAULT 0,
	PRIMARY KEY(`VersionID` AUTOINCREMENT)
)