var versions = [
    {
        "Abreviation": "AKJ",
        "Authors": "Michael Peter (Stone) Engelbrite",
        "Copyright": "Public Domain",
        "History": "The American King James Version (AKJ) isn't a new translation, but a revision of the classic 1611 King James Version (KJV) by Michael Peter (Stone) Engelbrite. Released in 1999, the AKJ aimed to bridge the gap between the beautiful, but sometimes archaic, English of the KJV and the speech patterns of modern Americans. Engelbrite believed in staying faithful to the original meaning, so he focused on updating spellings and vocabulary rather than changing sentence structure or grammar. This kept the familiar and beloved style of the KJV while making it more accessible for contemporary readers. Engelbrite released the AKJ into the public domain, allowing anyone to freely copy, distribute, or even modify it, as long as the core message remained unchanged.",
        "Status": 1,
        "Title": "American King James Version",
        "VerseCount": 31102,
        "VersionID": 1,
        "WikiLink": "https://www.angelfire.com/al4/allenkc/akjv/"
    },
    {
        "Abreviation": "ASV",
        "Authors": "Phillip Schaff and others.",
        "Copyright": "Public Domain",
        "History": "The American Standard Version (ASV) of the Bible, began in 1872 as a project to revise the 1611 King James Version. Phillip Schaff, assembled a team of 30 American and British scholars representing various Protestant denominations, and their efforts culminated in the publication of the revised New Testament in 1881 and the Old Testament in 1885, which was published in Great Britain as the Revised Version. However, the American scholars had suggested changes that were not included in the final British version. Consequently, they released their own version, the ASV, the New Testament was published in 1900 and the complete Bible in 1901. The ASV made use of the Westcott and Hort Greek New Testament and the Masoretic Text for the Old Testament, and it was the first major English translation to use \"Jehovah\" instead of God or Lord, as the Hebrew translation of YHWH. The ASV was popular at first, but it's archaic language limited its widespread adoption. It later served as the foundation for several 20th-century Bible translations, including the Revised Standard Version, the Amplified Bible, and the New American Standard Bible. Its commitment to a word-for-word translation philosophy has shaped modern Bible translations, balancing the need for literal accuracy with readability. Today, the ASV is in the public domain and it's freely available, and it continues to influence religious study and translation efforts.",
        "Status": 1,
        "Title": "American Standard Version",
        "VerseCount": 31102,
        "VersionID": 2,
        "WikiLink": "https://en.wikipedia.org/wiki/American_Standard_Version"
    },
    {
        "Abreviation": "BSB",
        "Authors": "Dr. Gary Hill, Dr. Maury Robertson, Dr. Eugene H. Merrill, Dr. Ulrik Sandborg-Petersen, Dr. Baruch Korman, and Dr. Grant Osborne. T, and others.",
        "Copyright": "Public Domain",
        "History": "The Berean Standard Bible (BSB) is a modern translation of the Holy Scriptures that emerged from a commitment to clarity and fidelity to the original Hebrew and Greek texts. Published in 2016, the BSB was developed by a team of scholars associated with Bible Hub and the Discover Bible. This translation is unique in its approach, merging the Berean Literal Bible and the Berean Interlinear Bible to create a version that is both accurate to the original languages and accessible to the modern reader. The BSB's name is inspired by the noble-minded Bereans of Acts 17:11, who diligently examined the Scriptures. Emphasizing this spirit of inquiry, the BSB offers a transparent text that encourages study of the root meanings of words. It is available for free online, reflecting the publishers' belief that the Scriptures should be freely studied and shared. The BSB stands out for its balance between \"word for word\" and \"thought for thought\" translation philosophies, maintaining original gender designations and consistency with the core meanings of the source texts. As language evolves, so does the BSB, with its translation process remaining open to refinement to ensure continued relevance and accuracy.",
        "Status": 1,
        "Title": "Berean Standard Bible",
        "VerseCount": 31102,
        "VersionID": 3,
        "WikiLink": "https://bereanbibles.com/about-berean-study-bible/"
    },
    {
        "Abreviation": "BBE",
        "Authors": "S. H. Hooke and others.",
        "Copyright": "Public Domain",
        "History": "The Bible in Basic English (BBE), first published in 1941, is a translation of the Bible into Basic English. It utilizes a 1,000-word vocabulary to help non-native English speakers and those with limited education. The New Testament was released in 1941, followed by the Old Testament in 1949. This translation was the work of S. H. Hooke and a team who sought to simplify the text while maintaining the original meanings. In 1965, the BBE was printed by Cambridge University Press and, due to the absence of a copyright notice, fell into the public domain in the United States. The BBE is noted for its clarity and simplicity, making the profound stories and teachings of the Bible accessible to a broader audience. It remains a valuable resource for introducing new readers to biblical narratives and concepts.",
        "Status": 1,
        "Title": "Bible in Basic English",
        "VerseCount": 31102,
        "VersionID": 4,
        "WikiLink": "https://en.wikipedia.org/wiki/Bible_in_Basic_English"
    },
    {
        "Abreviation": "BBB",
        "Authors": "Archbishop Matthew Parker and others.",
        "Copyright": "Public Domain",
        "History": "The Bishop's Bible (BBB), first published in 1568, was an English translation mandated by the Church of England to supplant the Geneva Bible, whose Calvinist-influenced annotations were deemed unsuitable by the Anglican clergy. Archbishop Matthew Parker spearheaded the project, which involved various bishops and scholars who each translated a section, identifiable by their initials in early editions. This translation was notably more formal and less accessible than its predecessor. Despite revisions in 1572, the BBB never achieved the popularity of the Geneva Bible. However, it significantly influenced the King James Version (KJV), with the 1602 edition of the Bishop's Bible serving as its base text. The KJV, completed in 1611, went on to become one of the most enduring and revered translations in the English-speaking world.",
        "Status": 1,
        "Title": "Bishop's Bible",
        "VerseCount": 31102,
        "VersionID": 5,
        "WikiLink": "https://en.wikipedia.org/wiki/Bishops%27_Bible"
    },
    {
        "Abreviation": "CBV",
        "Authors": "Myles Coverdale.",
        "Copyright": "Public Domain",
        "History": "The Coverdale Bible (CBV), completed by Myles Coverdale and published in 1535, holds the distinction of being the first complete Bible in Modern English and the first printed edition in the language. Coverdale's translation was groundbreaking, as it included both the Old and New Testaments. The work was not entirely original; it was heavily based on William Tyndale's earlier translations of the New Testament and parts of the Old Testament. For the remaining sections, Coverdale utilized a variety of sources, including Latin Vulgate, Martin Luther's German Bible, and the Swiss-German Zürich Bible. The 1535 edition's place of publication was initially disputed, but it is now attributed to Antwerp by Merten de Keyser. The CBV was later incorporated into the Great Bible of 1540 and remained influential in various religious texts, including several editions of the Book of Common Prayer. Over 20 editions of the CBV or its New Testament were published, with the last appearing in 1553.",
        "Status": 1,
        "Title": "Coverdale Bible",
        "VerseCount": 31102,
        "VersionID": 6,
        "WikiLink": "https://en.wikipedia.org/wiki/Coverdale_Bible"
    },
    {
        "Abreviation": "DBY",
        "Authors": "John Nelson Darby.",
        "Copyright": "Public Domain",
        "History": "The Darby Bible (DBY), an English translation by John Nelson Darby, was first published in 1890. Darby, an Anglo-Irish Bible teacher associated with the Plymouth Brethren, aimed to produce a modern translation for those without access to the original languages of Scripture. His translation began with the New Testament, published in 1867, followed by revisions in 1872 and 1884. Darby's work was not intended for public reading but for private study, and he typically used the King James Version in his oral ministry. The complete DBY, including the Old Testament translated by his students from his French and German versions, was published posthumously. Darby's translation is noted for its literal approach and for using \"Jehovah\" for the name of God, diverging from the common practice of using \"LORD\" or \"GOD\" in capital letters. This translation has influenced several other versions and remains a significant work for biblical scholars and students.",
        "Status": 1,
        "Title": "Darby English Bible",
        "VerseCount": 31099,
        "VersionID": 7,
        "WikiLink": "https://en.wikipedia.org/wiki/Darby_Bible"
    },
    {
        "Abreviation": "DRA",
        "Authors": "Gregory Martin, Cardinal William Allen, and members of the Catholic seminary English College, Douai, France. In 1749-1752 Richard Challoner, in 1790 Matthew Carey, and later others in the late 19th and early 20th centuries.",
        "Copyright": "Public Domain",
        "History": "The Douay-Rheims 1899 American Edition (DRA) Bible was a revision of the Douay-Rheims Bible (DRB), which was translated from the Latin Vulgate into English, and was primarily the work of Gregory Martin, an Oxford-trained scholar. Martin collaborated with other members of the Catholic seminary English College in Douai, France. Under the sponsorship of Cardinal William Allen, they produced the New Testament, which appeared in Rheims in 1582, and the Old Testament, published in Douai in 1609. Later English bishop Richard Challoner revised the translation between 1749 and 1752 to enhance its readability and comprehensibility. The Douay-Rheims Bible influenced the Authorized Version and was first published in America in 1790 by Mathew Carey of Philadelphia. Challoner's New Testament was, however, extensively revised by Bernard MacMahon in a series of Dublin editions from 1783 to 1810; and these various Dublin versions are the source of some Challoner bibles printed in the United States in the 19th Century. The Challoner revision of the Douay-Rheims is still often the Bible of choice of English-speaking Traditionalist Catholics. Several American editions followed, including the prominent Douay-Rheims 1899 American Edition (DRA).",
        "Status": 3,
        "Title": "Douay-Rheims 1899 American Version",
        "VerseCount": 35811,
        "VersionID": 8,
        "WikiLink": "https://hc.edu/publications/museums/Dunham_Bible_Museum/DBM_Bruno_MatthewCarey.pdf"
    },
    {
        "Abreviation": "DRB",
        "Authors": "William Allen, Richard Bristow, Thomas Worthington, William Reynolds, and others. Later Bishop Richard Challoner revised it.",
        "Copyright": "Public Domain",
        "History": "The Douay-Rheims Bible (DRB), a translation from the Latin Vulgate into English, was a monumental work undertaken by English Catholic scholars in exile. The New Testament was first published in Reims, France, in 1582, followed by the Old Testament in two volumes, released in 1609 and 1610 by the University of Douai. This translation was not only a religious text but also a political statement, supporting the Counter-Reformation during a time when Protestantism was gaining ground in England. The translation included extensive commentary and notes, aiming to uphold Catholic tradition. The Douay-Rheims Bible underwent a significant revision by Bishop Richard Challoner between 1749 and 1752, which improved its readability and accuracy by comparing it with Hebrew and Greek texts. This revised version, known as the Douay-Rheims-Challoner Bible, became the standard for English-speaking Catholics well into the 20th century. It holds the distinction of predating the King James Version and influencing it, despite the latter's attempt to distance itself from Catholic translations.",
        "Status": 1,
        "Title": "Douay-Rheims Bible",
        "VerseCount": 31102,
        "VersionID": 9,
        "WikiLink": "https://en.wikipedia.org/wiki/Douay%E2%80%93Rheims_Bible"
    },
    {
        "Abreviation": "ERV",
        "Authors": "Brooke Foss Westcott, Fenton John Anthony Hort, and others.",
        "Copyright": "Public Domain",
        "History": "The English Revised Version (ERV) of the Bible, also known as the Revised Version (RV), was a late-19th-century British revision of the King James Version (KJV). It was the first officially authorized and recognized revision of the KJV in Great Britain. The work involved over 50 scholars from various denominations in Great Britain, with American scholars contributing through correspondence. Notable members of the translation committee included Brooke Foss Westcott and Fenton John Anthony Hort. The New Testament was published in 1881, the Old Testament in 1885, and the Apocrypha in 1894.",
        "Status": 2,
        "Title": "English Revised Version",
        "VerseCount": 31102,
        "VersionID": 10,
        "WikiLink": "https://www.bible-researcher.com/erv.html"
    },
    {
        "Abreviation": "FBV",
        "Authors": "Dr. Jonathan Gallagher",
        "Copyright": "Public Domain",
        "History": "The Free Bible Version (FBV) prioritizes removing copyright restrictions on Bible translation. This allows anyone to use, share, and even reprint the text without copyright limitations. This contrasts with many Bible translations that have copyright restrictions, potentially limiting how freely people can distribute them. The FBV aims to deliver the scriptures in clear and understandable modern English, making it accessible to a wider audience.",
        "Status": 1,
        "Title": "Free Bible Version",
        "VerseCount": 31087,
        "VersionID": 11,
        "WikiLink": "https://www.freebibleversion.org/"
    },
    {
        "Abreviation": "GNV",
        "Authors": "William Whittingham, Myles Coverdale, and others.",
        "Copyright": "Public Domain",
        "History": "The Geneva Bible (GNV), a pivotal English translation, was first published in 1560 by Protestant exiles in Geneva. Fleeing the Catholic Mary I's reign, these scholars, under the spiritual guidance of John Calvin and later Theodore Beza, sought to continue the reformation of church and scripture. William Whittingham, along with Myles Coverdale and others, meticulously translated the Bible, which became known for its comprehensive annotations and vigorous language. This version, preceding the King James Bible (KJV) by 51 years, was the primary Bible for 16th-century English Protestantism and influenced figures like Shakespeare and Cromwell. It was notably brought to America on the Mayflower and even inspired the design for the Great Seal of the United States. Despite its popularity, it was not printed in England until 1576, due to the political-religious climate. The GNV's legacy persisted, impacting the translation of the KJV and remaining a beloved text for its clarity, that made it easily understood by non-scholars or clergy.",
        "Status": 1,
        "Title": "Geneva Bible",
        "VerseCount": 31102,
        "VersionID": 12,
        "WikiLink": "https://en.wikipedia.org/wiki/Geneva_Bible"
    },
    {
        "Abreviation": "JPS",
        "Authors": "Max Margolis, Solomon Schechter, Cyrus Adler, and others.",
        "Copyright": "Public Domain",
        "History": "The JPS Tanakh-OT 1917 (JPS) was the first Bible translation published by the Jewish Publication Society of America. It emerged from a desire to provide American Jews with a new and popular English rendition of the Bible. The translation's goal was to be accurate and reflect the Jewish traditions, feelings, law, and faith. The translation began in 1892 under the Central Conference of American Rabbis. Initially, individual rabbis and scholars were assigned different books, but progress was slow. In 1908, the Jewish Publication Society took over the project, and formed a committee of seven editors. Notable contributors included Max Margolis, Solomon Schechter, Cyrus Adler, and others. It was completed in 1915, the JPS 1917 translation became the Society’s best-selling volume, and sold nearly 40,000 copies within its first year. The JPS 1917 translation effectively became the standard Jewish translation for much of the 20th century.",
        "Status": 5,
        "Title": "JPS Tanakh-OT 1917",
        "VerseCount": 23145,
        "VersionID": 13,
        "WikiLink": "https://jps.org/books/holy-scriptures-tanakh-1917-edition/"
    },
    {
        "Abreviation": "KJA",
        "Authors": "Richard Bancroft, the archbishop of Canterbury, and 47 other scholars and clergy.",
        "Copyright": "Public Domain",
        "History": "The King James + Apocrypha (KJA) was the beginning of the King James Version (KJV), also known as the Authorized Version, which is an English translation of the Bible published in 1611 under the auspices of King James I of England. This translation had a significant influence on English literary style and was widely accepted as the standard English Bible from the mid-17th to the early 20th century1. It includes both the Old Testament and the New Testament. The Apocrypha are a selection of books that were originally published in the 1611 King James Bible. Positioned between the Old and New Testaments, the Apocrypha includes additional texts such as Tobit, Judith, Wisdom of Solomon, and others. The British and Foreign Bible Society, a major publisher of Bibles, stopped including the Apocrypha in many editions around 1820s due to cost concerns and theological disagreements. Over time, other publishers followed suit. The Apocrypha was part of the KJV for 274 years until it was finally removed from most modern editions of the KJV by 1885.",
        "Status": 5,
        "Title": "King James + Apocrypha",
        "VerseCount": 36822,
        "VersionID": 14,
        "WikiLink": "https://en.wikipedia.org/wiki/Biblical_apocrypha"
    },
    {
        "Abreviation": "KJV",
        "Authors": "Richard Bancroft, the archbishop of Canterbury, and 47 other scholars and clergy.",
        "Copyright": "Public Domain",
        "History": "The King James Version (KJV) of the Bible emerged in early 17th century England. King James I wanted to settle religious disputes and unify the country under a single Bible translation, so he commissioned the project in 1604. Prior English translations existed, but some were considered inaccurate or politically motivated. The KJV sought to be a scholarly and authoritative version. Dozens of translators worked from existing Hebrew and Greek texts, and the resulting text aimed for both accuracy and elegance. Published in 1611, the KJV quickly gained popularity.",
        "Status": 1,
        "Title": "King James Version",
        "VerseCount": 31102,
        "VersionID": 15,
        "WikiLink": "https://en.wikipedia.org/wiki/King_James_Version"
    },
    {
        "Abreviation": "LSV",
        "Authors": "Covenant Press",
        "Copyright": "Public Domain",
        "History": "The Literal Standard Version (LSV) is a Modern English translation of the Bible with several distinctive features. It positions itself as the most literal translation of the Bible into modern English. The first edition was published on February 2, 20201. The LSV aims for formal equivalence, preserving the original autographic meaning as closely as possible. It adheres to inerrancy and infallibility, recognizing these apply primarily to the original Hebrew, Aramaic, and Greek autographs. Accurately transliterates the proper Name of God (“YHWH”) without assuming a subjective pronunciation. A U.S. copyright was obtained in January 2020, but the LSV was subsequently released under the Creative Commons Attribution-ShareAlike license (CC BY-SA).",
        "Status": 2,
        "Title": "Literal Standard Version",
        "VerseCount": 31104,
        "VersionID": 16,
        "WikiLink": "https://en.wikipedia.org/wiki/Literal_Standard_Version"
    },
    {
        "Abreviation": "NLB",
        "Authors": "God's Servant",
        "Copyright": "Public Domain",
        "History": "The New Life Bible (NLB) paraphrased translation was begun shortly after I had an encounter with the angel Gabriel during an extended stay in the hospital in 2018. I feel very strongly that God has called me to do this work, and I have dedicated myself to it since then. The Holy Spirit is my guiding influence in this endeavor. The Holy Spirit has revealed to me that God wants a new scripture with a much softer and more forgiving tone than the traditional Scriptures. This is not a word for word translation of the Bible, but it is a faithful translation of the Bible. I have analyzed each verse and have faithfully recorded what it says to me through the Holy Spirit. I have rewritten each verse in such a way that I can understand what God is saying to me. It's a translation for me and anyone else, who finds the King James Version (KJV) to be very confusing and difficult to understand. This translation uses modern 21st century English, grammar, punctuation, and removes a lot of redundancy, repetion, and run-on sentences within the verses of the ancient texts. I am trying to restructure the sentences with the proper English positioning of Nouns, Pronouns, Verbs, Adverbs, Adjectives, Modifiers, and Descriptors.",
        "Status": 0,
        "Title": "New Life Bible",
        "VerseCount": 31102,
        "VersionID": 17,
        "WikiLink": ""
    },
    {
        "Abreviation": "NWB",
        "Authors": "Noah Webster",
        "Copyright": "Public Domain",
        "History": "The Noah Webster's Bible (NWB), was written by Noah Webster, was renowned for his dictionary, but he also made a significant contribution to biblical literature. In 1833, he published his own version of the Bible, which was not a new translation but a revision of the King James Version (KJV). Webster's primary goal was to modernize the language of the KJV, which had been the standard for over 200 years. He sought to clarify the text by updating archaic language, correcting grammatical inaccuracies, and removing words and phrases that were no longer in common use or could be considered offensive. Webster believed that the Bible should be accessible to the common person without the need for commentaries to understand its language. His version maintained the familiar style of the KJV but aimed to make it more comprehensible for the average reader of his time. Despite his efforts, the NWB never achieved the popularity of the KJV, largely due to the deep-seated affection and familiarity the public held for the original version. Nevertheless, Webster's edition remains a noteworthy attempt at making the Bible more approachable for everyday readers. ",
        "Status": 1,
        "Title": "Noah Webster's Bible",
        "VerseCount": 31106,
        "VersionID": 18,
        "WikiLink": "https://en.wikipedia.org/wiki/Webster%27s_Revision"
    },
    {
        "Abreviation": "SLT",
        "Authors": "Julia E. Smith",
        "Copyright": "Public Domain",
        "History": "The Smith's Literal Translation (SLT) of the Bible is a monumental work by Julia E. Smith, who became the first woman to translate the entire Bible into English. Her translation journey began in 1847, driven by a desire for a more literal interpretation of the scriptures. She was proficient in Latin, Greek, and Hebrew, and undertook this colossal eight-year task and completed it in 1855. Her approach was unique for its strict literalism, aiming to translate each Greek or Hebrew word consistently with the same English word. This method resulted in a translation that some found mechanical but was groundbreaking in its fidelity to the original texts. The translation was published in 1876 as \"The Holy Bible: Containing the Old and New Testaments; Translated Literally from the Original Tongues.\" Smith's work is not only a significant contribution to biblical scholarship but also a testament to her dedication and scholarly rigor.",
        "Status": 1,
        "Title": "Smith's Literal Translation",
        "VerseCount": 31102,
        "VersionID": 19,
        "WikiLink": "https://en.wikipedia.org/wiki/Julia_E._Smith_Parker_Translation"
    },
    {
        "Abreviation": "T4T",
        "Authors": "International Conference of Wycliffe Bible Translators",
        "Copyright": "Public Domain",
        "History": "The Translation for Translators (T4T) is a unique resource developed by Wycliffe Bible Translators specifically to aid Bible translation into other languages. In 1999 Wycliffe Bible Translators adopted \"Vision 2025\" project which aimed to start Bible translation projects into every language by 2025. Recognizing that most translation work would be done by native speakers, they developed the T4T to provide a source text specifically designed for translators.",
        "Status": 1,
        "Title": "Translation for Translators",
        "VerseCount": 30640,
        "VersionID": 20,
        "WikiLink": "http://bible.ink/version/info.html?T4T"
    },
    {
        "Abreviation": "TYN",
        "Authors": "William Tyndale",
        "Copyright": "Public Domain",
        "History": "The Tyndale Bible (TYN), a cornerstone in the history of the English Bible, was the work of William Tyndale, who, in the early 16th century, sought to translate the scriptures directly from Hebrew and Greek texts into English, a venture that was both revolutionary and dangerous at the time. Tyndale's translation was the first to take advantage of the printing press, leading to its wide distribution. Despite the lack of official approval and the Catholic Church's resistance, Tyndale's work laid the foundation for subsequent English translations. His New Testament was completed in 1526, with revised editions in 1534 and 1536. Tyndale also translated the Pentateuch and, before his execution for heresy in 1536, had worked on other Old Testament books. His translations were later used in the Matthew Bible and influenced future versions, including the King James Bible. Tyndale's commitment to making the Bible accessible to the English-speaking layperson changed the religious landscape forever, democratizing access to the scriptures and shaping the English language itself.",
        "Status": 5,
        "Title": "Tyndale's Bible",
        "VerseCount": 13928,
        "VersionID": 21,
        "WikiLink": "https://en.wikipedia.org/wiki/Tyndale_Bible"
    },
    {
        "Abreviation": "ULB",
        "Authors": "Many contributors, see ULBLicense.md",
        "Copyright": "Public Domain",
        "History": "The Unlocked Literal Bible (ULB) is a relatively recent translation project with a focus on open access and a unique approach.The Project began in 2013 as a project of the unfoldingWord organization, formerly known as Distant Shores Media. The ULB prioritizes two key objectives, it aims to present the Bible text in a way that closely reflects the word order and structure of the original Hebrew and Greek language texts.",
        "Status": 2,
        "Title": "Unlocked Literal Bible",
        "VerseCount": 31078,
        "VersionID": 22,
        "WikiLink": "https://www.mnnonline.org/news/a-new-source-for-bible-translation/"
    },
    {
        "Abreviation": "WEY",
        "Authors": "Richard Francis Weymouth, James Alexander Robertson, and many others.",
        "Copyright": "Public Domain",
        "History": "The Weymouth New Testament (WNT), also known as \"The New Testament in Modern Speech\" or \"The Modern Speech New Testament,\" has a history rooted in the late 19th and early 20th centuries. Richard Francis Weymouth (1822-1902) was a philologist (language expert) and biblical scholar, who was Weymouth was a Baptist layman and the headmaster of a London school. Weymouth wanted to create a New Testament translation in clear, understandable English for the general public. He wanted it to reflect how the inspired writers might have expressed themselves in 19th-century English. Weymouth translated the Greek text into English, aiming for a clear and natural style. The translation, along with editorial work by Ernest Hampden-Cook, was published in 1903. The WNT prioritizes using everyday English that is readily understandable to modern readers. The WNT has undergone several revisions since its initial publication. Some notable editions include the 1924 revision by scholars and the 1929 revision by James Alexander Robertson.",
        "Status": 5,
        "Title": "Weymouth New Testament",
        "VerseCount": 7957,
        "VersionID": 23,
        "WikiLink": "https://en.wikipedia.org/wiki/Weymouth_New_Testament"
    },
    {
        "Abreviation": "WEB",
        "Authors": "Michael Paul Johnson",
        "Copyright": "Public Domain",
        "History": "The World English Bible (WEB) is a modern English translation of the Bible that began in 1994 and was completed in 2020. It was initiated by Michael Paul Johnson, who felt a divine call to create a freely distributable English Bible. Without formal training, Johnson studied Greek and Hebrew and utilized scholarly works to start translating the New Testament. He shared his drafts online, incorporating feedback from volunteers. Realizing the enormity of the task, he decided to base his work on the American Standard Version (ASV) of 1901, which was in the public domain and known for its accuracy. Johnson's goal was to modernize the language of the ASV, which he began by creating custom computer programs to assist in the process. The initial draft, named the World English Bible, aimed to be accessible to all English speakers and was distributed via the internet. The WEB includes both American and British English versions and offers two Old Testament types: one with the protocanon and another with apocrypha.",
        "Status": 1,
        "Title": "World English Bible",
        "VerseCount": 31102,
        "VersionID": 24,
        "WikiLink": "https://en.wikipedia.org/wiki/World_English_Bible"
    },
    {
        "Abreviation": "YLT",
        "Authors": "Robert Young",
        "Copyright": "Public Domain",
        "History": "The Young's Literal Translation (YLT) of the Bible is a unique work that stands out for its commitment to textual fidelity. Published in 1862 by Robert Young, the YLT was born out of a desire to render the scriptures as closely to the original texts as possible. Young, a self-taught scholar proficient in ancient languages, utilized the Textus Receptus and the Masoretic Text as the foundation for his translation. His approach was to maintain the tenses and idioms of the original languages, which often resulted in a translation that, while accurate, could be challenging to read due to its strict adherence to the source texts. The YLT underwent revisions, with a notable one in 1887, and a posthumous revision in 1898, ten years after Young's death. These revisions aimed to refine the translation without deviating from Young's original principles of literal translation. In 2020, a major revision called the Literal Standard Version was released, updating the YLT for contemporary readers while maintaining its literal approach. The YLT's legacy is its contribution to a more nuanced understanding of biblical texts, offering insights typically reserved for those familiar with the original languages.",
        "Status": 1,
        "Title": "Young's Literal Translation",
        "VerseCount": 31103,
        "VersionID": 25,
        "WikiLink": "https://en.wikipedia.org/wiki/Young%27s_Literal_Translation"
    }
];